// Auto-generated by Export-Data.ps1 - do not edit by hand
window.MRA_DATA = {
    "generatedAt":  "2026-06-11T10:58:34",
    "generatedText":  "Thu Jun 11, 2026  10:58 AM",
    "todayISO":  "2026-06-11",
    "physicalBays":  [
                         "Bay 2 Front",
                         "Bay 2 Back",
                         "Bay 3 Front",
                         "Bay 3 Back",
                         "Bay 4 Front",
                         "Bay 4 Back",
                         "Bay 5 Front",
                         "Bay 5 Back",
                         "Parking Lot",
                         "On Hold/Off-Site"
                     ],
    "jobs":  [
                 {
                     "row":  4,
                     "bay":  "Parking Lot",
                     "project":  "Siemens #3005 – Side Sampler Install",
                     "client":  "Siemens DX #3005",
                     "jobNum":  "J1110W",
                     "status":  "Shipped",
                     "pm":  "",
                     "startISO":  "2026-05-30",
                     "completionISO":  "2026-06-05",
                     "startText":  "05/30/26",
                     "completionText":  "06/05/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  3,
                     "salOpen":  0
                 },
                 {
                     "row":  5,
                     "bay":  "Parking Lot",
                     "project":  "Medtronic",
                     "client":  "Medtronic",
                     "jobNum":  "J1553",
                     "status":  "Active",
                     "pm":  "Megan Fraser",
                     "startISO":  "2026-06-02",
                     "completionISO":  "2026-06-12",
                     "startText":  "06/02/26",
                     "completionText":  "06/12/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  6,
                     "bay":  "Parking Lot",
                     "project":  "Oakland Schools – Client Visit",
                     "client":  "Oakland Schools",
                     "jobNum":  "J1420",
                     "status":  "Shipped",
                     "pm":  "Luciana Giglio",
                     "startISO":  "2026-06-08",
                     "completionISO":  "2026-06-12",
                     "startText":  "06/08/26",
                     "completionText":  "06/12/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  7,
                     "bay":  "Parking Lot",
                     "project":  "SWC FL1 (1545) – Maintenance",
                     "client":  "SWC Florida 1",
                     "jobNum":  "J1514",
                     "status":  "Active",
                     "pm":  "Stephanie Hardie",
                     "startISO":  "2026-06-03",
                     "completionISO":  "2026-06-25",
                     "startText":  "06/03/26",
                     "completionText":  "06/25/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  8,
                     "bay":  "Parking Lot",
                     "project":  "Callaway Parking – Issue #961",
                     "client":  "Callaway",
                     "jobNum":  "1484",
                     "status":  "Scheduled",
                     "pm":  "Frank Mancina/Mark St Jean",
                     "startISO":  "2026-06-10",
                     "completionISO":  "2026-06-19",
                     "startText":  "06/10/26",
                     "completionText":  "06/19/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  9,
                     "bay":  "Parking Lot",
                     "project":  "Powertech Gen Sound Baffle",
                     "client":  "Tony",
                     "jobNum":  "Tony *1",
                     "status":  "Scheduled",
                     "pm":  "",
                     "startISO":  "2026-06-05",
                     "completionISO":  "2026-06-16",
                     "startText":  "06/05/26",
                     "completionText":  "06/16/26",
                     "category":  "bay",
                     "openTasks":  [
                                       "1. Sal - Custom Sal jr designs. Mock up complete and tested and reduced sound by ~25db. Mocking up phase 2 next (thicker, etc)."
                                   ],
                     "openCount":  1,
                     "doneCount":  0,
                     "salOpen":  1
                 },
                 {
                     "row":  10,
                     "bay":  "Parking Lot",
                     "project":  "Medtronic – Vendor Setup",
                     "client":  "Medtronic",
                     "jobNum":  "J1553",
                     "status":  "Scheduled",
                     "pm":  "Megan Fraser",
                     "startISO":  "2026-06-05",
                     "completionISO":  "2026-10-02",
                     "startText":  "06/05/26",
                     "completionText":  "10/02/26",
                     "category":  "bay",
                     "openTasks":  [
                                       "3. Sal - Remove wood ceiling.",
                                       "4. Sal - Remove floor metal track system.",
                                       "5. Sal - Remove ADA lift (Save).",
                                       "6. Sal - Check floor hinge rivets (popped out) from underside, etc."
                                   ],
                     "openCount":  4,
                     "doneCount":  2,
                     "salOpen":  4
                 },
                 {
                     "row":  11,
                     "bay":  "Parking Lot",
                     "project":  "Oakland Schools – Revamp",
                     "client":  "Oakland Schools",
                     "jobNum":  "J1420",
                     "status":  "Scheduled",
                     "pm":  "TBD",
                     "startISO":  "2026-06-08",
                     "completionISO":  "2026-08-21",
                     "startText":  "06/08/26",
                     "completionText":  "08/21/26",
                     "category":  "bay",
                     "openTasks":  [
                                       "3. - Sal - Remove all interior graphics and floor carpet."
                                   ],
                     "openCount":  1,
                     "doneCount":  2,
                     "salOpen":  1
                 },
                 {
                     "row":  12,
                     "bay":  "On Hold/Off-Site",
                     "project":  "SMC Corporation – Return for QC",
                     "client":  "SMC Corporation",
                     "jobNum":  "1542",
                     "status":  "On Hold",
                     "pm":  "Al Karloff",
                     "startISO":  null,
                     "completionISO":  null,
                     "startText":  "",
                     "completionText":  "",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  13,
                     "bay":  "On Hold/Off-Site",
                     "project":  "Siemens Big Betty – Maint./Prep",
                     "client":  "MRA Internal",
                     "jobNum":  "J1014",
                     "status":  "On Hold",
                     "pm":  "TBD",
                     "startISO":  null,
                     "completionISO":  null,
                     "startText":  "",
                     "completionText":  "",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  15,
                     "bay":  "On Hold/Off-Site",
                     "project":  "SENO Medical – Indoor Space Req.",
                     "client":  "SENO Medical – Box Truck",
                     "jobNum":  "J1541",
                     "status":  "On Hold",
                     "pm":  "Alex Karam",
                     "startISO":  "2026-04-07",
                     "completionISO":  "2026-06-12",
                     "startText":  "04/07/26",
                     "completionText":  "06/12/26",
                     "category":  "bay",
                     "openTasks":  [
                                       "1.  Confirm MRA license plate"
                                   ],
                     "openCount":  1,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  16,
                     "bay":  "Bay 5 Front",
                     "project":  "Baltimore Aircoil – HVAC Maint.",
                     "client":  "Baltimore Aircoil",
                     "jobNum":  "J1555",
                     "status":  "Shipped",
                     "pm":  "",
                     "startISO":  "2026-06-04",
                     "completionISO":  "2026-06-05",
                     "startText":  "06/04/26",
                     "completionText":  "06/05/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  5,
                     "salOpen":  0
                 },
                 {
                     "row":  17,
                     "bay":  "Bay 5 Front",
                     "project":  "Travis Mathew – Maint. Items",
                     "client":  "TravisMathew",
                     "jobNum":  "J1387",
                     "status":  "Scheduled",
                     "pm":  "Frank Mancina",
                     "startISO":  "2026-06-05",
                     "completionISO":  "2026-06-12",
                     "startText":  "06/05/26",
                     "completionText":  "06/12/26",
                     "category":  "bay",
                     "openTasks":  [
                                       "1. Sal - 5th wheel corner damage / Generator plate repair. Front Damaged. Wrap with matte wrap when complete.",
                                       "2. Electricians - Secure rear camera data run properly (currently behind lights. Clip to bottom of rail to hide.",
                                       "3. Sal - Exterior panels bowing. Rivet as require and then cover with black matte vinyl.",
                                       "4. Sal- Skirt replacement. Validate existing skirt studs. Verify fit.",
                                       "5. Sal - DOT Tape replacement.",
                                       "6. Sal - Glue corner interior trim piece that keeps falling off.",
                                       "7. Sal - Hydaulic leak clean up and repair in belly pan area",
                                       "8. Sal - Seal replacement - Expandable and rear door)",
                                       "9. Sal - Replacement of rubber bumpers on expandable jacks"
                                   ],
                     "openCount":  9,
                     "doneCount":  0,
                     "salOpen":  8
                 },
                 {
                     "row":  18,
                     "bay":  "Bay 5 Front",
                     "project":  "Siemens DI – Pedestals/Maint.",
                     "client":  "Siemens DI",
                     "jobNum":  "J1524",
                     "status":  "Scheduled",
                     "pm":  "Megan Fraser",
                     "startISO":  "2026-07-06",
                     "completionISO":  "2026-07-10",
                     "startText":  "07/06/26",
                     "completionText":  "07/10/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  19,
                     "bay":  "Bay 5 Back",
                     "project":  "6160 Kentucky Expandable Trailer 2022 Boston Scientific DX",
                     "client":  "Boston Scientific DX",
                     "jobNum":  "J1507",
                     "status":  "Scheduled",
                     "pm":  "Alex Karam",
                     "startISO":  "2026-06-08",
                     "completionISO":  "2026-06-12",
                     "startText":  "06/08/26",
                     "completionText":  "06/12/26",
                     "category":  "bay",
                     "openTasks":  [
                                       "1. Sal - Fleetio #939 - John discovered two separate large leaks in Houston. Sal investigating. Torn roof multiple locations. Repaired 6/10. Need doug to pull out trailer and Sal will verify roof leak.",
                                       "4. Doug - Pull out trailer to allow for roof leak validation."
                                   ],
                     "openCount":  2,
                     "doneCount":  2,
                     "salOpen":  1
                 },
                 {
                     "row":  20,
                     "bay":  "Bay 5 Back",
                     "project":  "Generator Painting \u0026 Mount – 6821",
                     "client":  "Oakland Schools",
                     "jobNum":  "J1420",
                     "status":  "TBD",
                     "pm":  "Luciana Giglio",
                     "startISO":  null,
                     "completionISO":  null,
                     "startText":  "",
                     "completionText":  "",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  21,
                     "bay":  "Bay 5 Back",
                     "project":  "Generator Swap – 9639 Tractor",
                     "client":  "Siemens DX #3005",
                     "jobNum":  "J1110W",
                     "status":  "Active",
                     "pm":  "",
                     "startISO":  "2026-06-01",
                     "completionISO":  "2026-06-05",
                     "startText":  "06/01/26",
                     "completionText":  "06/05/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  22,
                     "bay":  "Bay 4 Back",
                     "project":  "Lexcare Infowheels",
                     "client":  "LexCare Hearoes",
                     "jobNum":  "1546",
                     "status":  "Shipped",
                     "pm":  "",
                     "startISO":  "2026-02-02",
                     "completionISO":  "2026-06-04",
                     "startText":  "02/02/26",
                     "completionText":  "06/04/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  2,
                     "salOpen":  0
                 },
                 {
                     "row":  23,
                     "bay":  "Bay 4 Front",
                     "project":  "Pod 86 – (Cisco)",
                     "client":  "MRA Internal",
                     "jobNum":  "J1558",
                     "status":  "Active",
                     "pm":  "Al Karloff",
                     "startISO":  "2026-06-02",
                     "completionISO":  "2026-06-12",
                     "startText":  "06/02/26",
                     "completionText":  "06/12/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  2,
                     "salOpen":  0
                 },
                 {
                     "row":  24,
                     "bay":  "Bay 4 Back",
                     "project":  "Tim McGraw – Trailer Relaunch",
                     "client":  "Tim McGraw",
                     "jobNum":  "J1421",
                     "status":  "Active",
                     "pm":  "Luciana Giglio",
                     "startISO":  "2026-05-11",
                     "completionISO":  "2026-06-26",
                     "startText":  "05/11/26",
                     "completionText":  "06/26/26",
                     "category":  "bay",
                     "openTasks":  [
                                       "2. Wrap team. Graphics sent over on 6/9 . Need to print and wrap."
                                   ],
                     "openCount":  1,
                     "doneCount":  1,
                     "salOpen":  0
                 },
                 {
                     "row":  25,
                     "bay":  "Bay 3 Front",
                     "project":  "ABB – Maintenance Items",
                     "client":  "ABB",
                     "jobNum":  "J1407",
                     "status":  "Shipped",
                     "pm":  "",
                     "startISO":  "2026-06-03",
                     "completionISO":  "2026-06-05",
                     "startText":  "06/03/26",
                     "completionText":  "06/05/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  3,
                     "salOpen":  0
                 },
                 {
                     "row":  26,
                     "bay":  "Bay 3 Front",
                     "project":  "QuidelOrtho – Decommission",
                     "client":  "QuidelOrtho",
                     "jobNum":  "J1384",
                     "status":  "Scheduled",
                     "pm":  "Sherri Washington",
                     "startISO":  "2026-06-09",
                     "completionISO":  "2026-06-11",
                     "startText":  "06/09/26",
                     "completionText":  "06/11/26",
                     "category":  "bay",
                     "openTasks":  [
                                       "2. Sal - Equipment pull out after review once arrived. All equipment tagged with blue tape. Remove all track on back wall. See Rich for Walkthru",
                                       "3. Lindsey 360 walk around, record view.",
                                       "4. Josh and Jeff - Store equipment for Debby. Will send pallets and then we need wrap for shipment. date TBD."
                                   ],
                     "openCount":  3,
                     "doneCount":  1,
                     "salOpen":  1
                 },
                 {
                     "row":  27,
                     "bay":  "Bay 3 Back",
                     "project":  "Washtenaw County",
                     "client":  "Washtenaw Comm. College",
                     "jobNum":  "J1543",
                     "status":  "Active",
                     "pm":  "Megan Fraser",
                     "startISO":  "2026-02-24",
                     "completionISO":  "2026-06-12",
                     "startText":  "02/24/26",
                     "completionText":  "06/12/26",
                     "category":  "bay",
                     "openTasks":  [
                                       "1.  Electrical – Light (ceiling) swap. Pass Front side door ceiling entrance",
                                       "2 - Wrap team - Driver side 80% complete. Pass side 80% complete. Inside 95 % complete. Confirmed will be complete by Friday. Pushing for early friday.",
                                       "5. Sal - Starlink. Need to raise to roof level per review 6/8 (morning). Allow for clear path to satillites. REmoved on 6/8 for wrap team. Will reinstall following.",
                                       "6. Techtronic - LED Baffles. Review on 6/5. To return week of 6/8 (early) to remove and install track/baffle,etc. Proper install."
                                   ],
                     "openCount":  4,
                     "doneCount":  5,
                     "salOpen":  1
                 },
                 {
                     "row":  28,
                     "bay":  "Bay 3 Back",
                     "project":  "Medtronic – Buildout",
                     "client":  "Medtronic",
                     "jobNum":  "J1553",
                     "status":  "Scheduled",
                     "pm":  "Megan Fraser",
                     "startISO":  "2026-06-15",
                     "completionISO":  "2026-11-13",
                     "startText":  "06/15/26",
                     "completionText":  "11/13/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  29,
                     "bay":  "Bay 2 Front",
                     "project":  "Post ADLM Inventory Storage",
                     "client":  "Siemens Global Warehousing",
                     "jobNum":  "J1391",
                     "status":  "Scheduled",
                     "pm":  "Cindy Irland",
                     "startISO":  "2026-06-22",
                     "completionISO":  "2026-07-17",
                     "startText":  "06/22/26",
                     "completionText":  "07/17/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  30,
                     "bay":  "Bay 2 Front",
                     "project":  "Pre ADLM Inventory Storage",
                     "client":  "Siemens Global Warehousing",
                     "jobNum":  "J1391",
                     "status":  "Scheduled",
                     "pm":  "Cindy Irland",
                     "startISO":  "2026-08-05",
                     "completionISO":  "2026-08-21",
                     "startText":  "08/05/26",
                     "completionText":  "08/21/26",
                     "category":  "bay",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  31,
                     "bay":  "APL/Holidays",
                     "project":  "John Tindle – APL",
                     "client":  "APL/Holidays",
                     "jobNum":  "",
                     "status":  "Leave",
                     "pm":  "N/A",
                     "startISO":  "2026-06-04",
                     "completionISO":  "2026-06-05",
                     "startText":  "06/04/26",
                     "completionText":  "06/05/26",
                     "category":  "leave",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  32,
                     "bay":  "APL/Holidays",
                     "project":  "Al Karloff – APL",
                     "client":  "APL/Holidays",
                     "jobNum":  "",
                     "status":  "Leave",
                     "pm":  "N/A",
                     "startISO":  "2026-06-12",
                     "completionISO":  "2026-06-12",
                     "startText":  "06/12/26",
                     "completionText":  "06/12/26",
                     "category":  "leave",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  33,
                     "bay":  "APL/Holidays",
                     "project":  "Brandon Kosal – APL",
                     "client":  "APL/Holidays",
                     "jobNum":  "",
                     "status":  "Leave",
                     "pm":  "N/A",
                     "startISO":  "2026-06-12",
                     "completionISO":  "2026-06-19",
                     "startText":  "06/12/26",
                     "completionText":  "06/19/26",
                     "category":  "leave",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  34,
                     "bay":  "APL/Holidays",
                     "project":  "Megan Fraser – APL",
                     "client":  "APL/Holidays",
                     "jobNum":  "",
                     "status":  "Leave",
                     "pm":  "N/A",
                     "startISO":  "2026-06-15",
                     "completionISO":  "2026-06-15",
                     "startText":  "06/15/26",
                     "completionText":  "06/15/26",
                     "category":  "leave",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  35,
                     "bay":  "APL/Holidays",
                     "project":  "Doug Cooley – APL",
                     "client":  "APL/Holidays",
                     "jobNum":  "",
                     "status":  "Leave",
                     "pm":  "N/A",
                     "startISO":  "2026-06-19",
                     "completionISO":  "2026-06-22",
                     "startText":  "06/19/26",
                     "completionText":  "06/22/26",
                     "category":  "leave",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  36,
                     "bay":  "APL/Holidays",
                     "project":  "Micayla Roe – APL",
                     "client":  "APL/Holidays",
                     "jobNum":  "",
                     "status":  "Leave",
                     "pm":  "N/A",
                     "startISO":  "2026-06-24",
                     "completionISO":  "2026-07-01",
                     "startText":  "06/24/26",
                     "completionText":  "07/01/26",
                     "category":  "leave",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  37,
                     "bay":  "APL/Holidays",
                     "project":  "Al Karloff – APL",
                     "client":  "APL/Holidays",
                     "jobNum":  "",
                     "status":  "Leave",
                     "pm":  "N/A",
                     "startISO":  "2026-06-29",
                     "completionISO":  "2026-07-02",
                     "startText":  "06/29/26",
                     "completionText":  "07/02/26",
                     "category":  "leave",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  38,
                     "bay":  "APL/Holidays",
                     "project":  "Al Karloff – APL",
                     "client":  "APL/Holidays",
                     "jobNum":  "",
                     "status":  "Leave",
                     "pm":  "N/A",
                     "startISO":  "2026-08-01",
                     "completionISO":  "2026-08-03",
                     "startText":  "08/01/26",
                     "completionText":  "08/03/26",
                     "category":  "leave",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  39,
                     "bay":  "APL/Holidays",
                     "project":  "Al Karloff – APL",
                     "client":  "APL/Holidays",
                     "jobNum":  "",
                     "status":  "Leave",
                     "pm":  "N/A",
                     "startISO":  "2026-10-05",
                     "completionISO":  "2026-10-09",
                     "startText":  "10/05/26",
                     "completionText":  "10/09/26",
                     "category":  "leave",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  40,
                     "bay":  "APL/Holidays",
                     "project":  "Ted O\u0027Malley – APL",
                     "client":  "APL/Holidays",
                     "jobNum":  "",
                     "status":  "Leave",
                     "pm":  "N/A",
                     "startISO":  "2026-10-14",
                     "completionISO":  "2026-10-20",
                     "startText":  "10/14/26",
                     "completionText":  "10/20/26",
                     "category":  "leave",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  41,
                     "bay":  "APL/Holidays",
                     "project":  "Ted O\u0027Malley – APL",
                     "client":  "APL/Holidays",
                     "jobNum":  "",
                     "status":  "Leave",
                     "pm":  "N/A",
                     "startISO":  "2026-11-09",
                     "completionISO":  "2026-11-17",
                     "startText":  "11/09/26",
                     "completionText":  "11/17/26",
                     "category":  "leave",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  42,
                     "bay":  "Next Up",
                     "project":  "Stryker - Rewrap",
                     "client":  "Stryker",
                     "jobNum":  "J1412",
                     "status":  "Scheduled",
                     "pm":  "Megan Fraser",
                     "startISO":  "2026-10-12",
                     "completionISO":  "2026-10-30",
                     "startText":  "10/12/26",
                     "completionText":  "10/30/26",
                     "category":  "pipeline",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  43,
                     "bay":  "Next Up",
                     "project":  "AWS Revamp",
                     "client":  "AWS",
                     "jobNum":  "J1217",
                     "status":  "Scheduled",
                     "pm":  "TBD",
                     "startISO":  "2026-07-31",
                     "completionISO":  "2026-09-08",
                     "startText":  "07/31/26",
                     "completionText":  "09/08/26",
                     "category":  "pipeline",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  44,
                     "bay":  "Next Up",
                     "project":  "County of Essex - Generator Swap",
                     "client":  "County of Essex",
                     "jobNum":  "J1467",
                     "status":  "Scheduled",
                     "pm":  "Sherrill Buchan",
                     "startISO":  "2026-07-13",
                     "completionISO":  "2026-07-17",
                     "startText":  "07/13/26",
                     "completionText":  "07/17/26",
                     "category":  "pipeline",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  45,
                     "bay":  "Next Up",
                     "project":  "Mammo Mandy - Maintenance Week",
                     "client":  "Siemens Mammo Mandy",
                     "jobNum":  "J1424",
                     "status":  "Scheduled",
                     "pm":  "Mitch Schirr",
                     "startISO":  "2026-08-31",
                     "completionISO":  "2026-09-11",
                     "startText":  "08/31/26",
                     "completionText":  "09/11/26",
                     "category":  "pipeline",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  46,
                     "bay":  "Next Up",
                     "project":  "SWC HI - Final Finishes",
                     "client":  "SWC Hawaii",
                     "jobNum":  "J1512",
                     "status":  "Scheduled",
                     "pm":  "TBD",
                     "startISO":  "2026-08-31",
                     "completionISO":  "2026-09-17",
                     "startText":  "08/31/26",
                     "completionText":  "09/17/26",
                     "category":  "pipeline",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  47,
                     "bay":  "N/A",
                     "project":  "SWC IL - Maintenance Updates",
                     "client":  "SWC Illinois",
                     "jobNum":  "J1422",
                     "status":  "Scheduled",
                     "pm":  "",
                     "startISO":  "2026-06-27",
                     "completionISO":  "2026-07-10",
                     "startText":  "06/27/26",
                     "completionText":  "07/10/26",
                     "category":  "pipeline",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  48,
                     "bay":  "Next Up",
                     "project":  "MOTT - Roof Repairs",
                     "client":  "MOTT",
                     "jobNum":  "J1428",
                     "status":  "Scheduled",
                     "pm":  "Heather Maloney",
                     "startISO":  "2026-06-08",
                     "completionISO":  "2026-06-26",
                     "startText":  "06/08/26",
                     "completionText":  "06/26/26",
                     "category":  "pipeline",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  49,
                     "bay":  "Next Up",
                     "project":  "AZ250/Trumpf - Analysis",
                     "client":  "Arizona 250",
                     "jobNum":  "J1554",
                     "status":  "TBD",
                     "pm":  "Al Karloff",
                     "startISO":  null,
                     "completionISO":  null,
                     "startText":  "",
                     "completionText":  "",
                     "category":  "pipeline",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  50,
                     "bay":  "Next Up",
                     "project":  "Ferguson BizBox - Graphic Updates",
                     "client":  "Ferguson BizBox",
                     "jobNum":  "J1557",
                     "status":  "Scheduled",
                     "pm":  "Luciana Giglio",
                     "startISO":  null,
                     "completionISO":  "2026-07-09",
                     "startText":  "",
                     "completionText":  "07/09/26",
                     "category":  "pipeline",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 },
                 {
                     "row":  51,
                     "bay":  "N/A",
                     "project":  "ABB DX - Electrical Swap",
                     "client":  "MRA Internal",
                     "jobNum":  "J1014",
                     "status":  "Scheduled",
                     "pm":  "",
                     "startISO":  null,
                     "completionISO":  "2026-07-09",
                     "startText":  "",
                     "completionText":  "07/09/26",
                     "category":  "pipeline",
                     "openTasks":  [

                                   ],
                     "openCount":  0,
                     "doneCount":  0,
                     "salOpen":  0
                 }
             ],
    "projects":  [
                     {
                         "name":  "Medtronic",
                         "pm":  "Megan Fraser",
                         "startISO":  "2026-06-01",
                         "finishISO":  "2026-12-14",
                         "taskCount":  101,
                         "doneCount":  33,
                         "pct":  33,
                         "milestones":  [
                                            {
                                                "name":  "Definitive Launch Date Determined, Per VE / MOU",
                                                "dateISO":  "2026-06-05"
                                            },
                                            {
                                                "name":  "Review, Comment and Approval of Finishes \u0026 Materials",
                                                "dateISO":  "2026-07-10"
                                            },
                                            {
                                                "name":  "Production of Exhibitry / Millwork",
                                                "dateISO":  "2026-08-07"
                                            },
                                            {
                                                "name":  "Deliver Technology Components / Technology Displays",
                                                "dateISO":  "2026-08-14"
                                            },
                                            {
                                                "name":  "Trailer Completion",
                                                "dateISO":  "2026-10-23"
                                            },
                                            {
                                                "name":  "Available to Travel to Soft Launch, MI Based, School TBD",
                                                "dateISO":  "2026-11-16"
                                            },
                                            {
                                                "name":  "First Event | Ribbon Cutting, MN, School TBD",
                                                "dateISO":  "2026-12-14"
                                            }
                                        ]
                     },
                     {
                         "name":  "Oakland Schools",
                         "pm":  "Megan Fraser",
                         "startISO":  "2026-05-15",
                         "finishISO":  "2026-09-08",
                         "taskCount":  29,
                         "doneCount":  6,
                         "pct":  21,
                         "milestones":  [
                                            {
                                                "name":  "Kickoff Meeting",
                                                "dateISO":  "2026-05-27"
                                            },
                                            {
                                                "name":  "Graphic Strike Approval",
                                                "dateISO":  "2026-06-26"
                                            },
                                            {
                                                "name":  "Trailer Completion",
                                                "dateISO":  "2026-08-21"
                                            },
                                            {
                                                "name":  "Available to Travel to Welcome Back Event",
                                                "dateISO":  "2026-08-31"
                                            },
                                            {
                                                "name":  "Soft Launch | Welcome Back Event",
                                                "dateISO":  "2026-09-02"
                                            },
                                            {
                                                "name":  "First Event | Relaunch",
                                                "dateISO":  "2026-09-08"
                                            }
                                        ]
                     },
                     {
                         "name":  "Trumpf",
                         "pm":  "Al Karloff",
                         "startISO":  "2026-05-26",
                         "finishISO":  "2026-10-21",
                         "taskCount":  89,
                         "doneCount":  3,
                         "pct":  3,
                         "milestones":  [
                                            {
                                                "name":  "Design Lock – Final approval of conceptual renderings / design direction",
                                                "dateISO":  "2026-06-19"
                                            },
                                            {
                                                "name":  "Tech SOW sign-off",
                                                "dateISO":  "2026-07-10"
                                            },
                                            {
                                                "name":  "Fabrication Complete",
                                                "dateISO":  "2026-08-31"
                                            },
                                            {
                                                "name":  "Technology integration \u0026 testing (power-on, AV routing, network, media load)",
                                                "dateISO":  "2026-09-04"
                                            },
                                            {
                                                "name":  "Client walkthrough \u0026 final acceptance",
                                                "dateISO":  "2026-09-11"
                                            },
                                            {
                                                "name":  "Trailer departs MRA → Art Guild (NJ)",
                                                "dateISO":  "2026-09-11"
                                            },
                                            {
                                                "name":  "Tour Launch – Las Vegas",
                                                "dateISO":  "2026-10-21"
                                            }
                                        ]
                     },
                     {
                         "name":  "Cisco",
                         "pm":  "Al Karloff",
                         "startISO":  "2026-05-24",
                         "finishISO":  "2026-11-06",
                         "taskCount":  91,
                         "doneCount":  0,
                         "pct":  0,
                         "milestones":  [
                                            {
                                                "name":  "G1 — Design Lock",
                                                "dateISO":  "2026-06-19"
                                            },
                                            {
                                                "name":  "G2 — Drawing Review 1 / Design Approved",
                                                "dateISO":  "2026-07-05"
                                            },
                                            {
                                                "name":  "G3 — Final Client Approval \u0026 BOM Frozen",
                                                "dateISO":  "2026-08-14"
                                            },
                                            {
                                                "name":  "G5 — Fabrication In-Process OK",
                                                "dateISO":  "2026-09-18"
                                            },
                                            {
                                                "name":  "G6 — MRA Integration Bench Tests Pass",
                                                "dateISO":  "2026-10-09"
                                            },
                                            {
                                                "name":  "G7 — Acceptance Test Pass (MRA Systems)",
                                                "dateISO":  "2026-10-26"
                                            },
                                            {
                                                "name":  "G8 — Commissioning / FAT Pass",
                                                "dateISO":  "2026-11-06"
                                            },
                                            {
                                                "name":  "G9 — MRA Departure-Ready",
                                                "dateISO":  "2026-11-06"
                                            }
                                        ]
                     },
                     {
                         "name":  "Washtenaw",
                         "pm":  "Megan Fraser",
                         "startISO":  "2026-06-08",
                         "finishISO":  "2026-06-12",
                         "taskCount":  6,
                         "doneCount":  0,
                         "pct":  0,
                         "milestones":  [
                                            {
                                                "name":  "Final assembly",
                                                "dateISO":  "2026-06-12"
                                            }
                                        ]
                     },
                     {
                         "name":  "Seimans DI Pedestal",
                         "pm":  "Megan Fraser",
                         "startISO":  "2026-06-02",
                         "finishISO":  "2026-06-20",
                         "taskCount":  2,
                         "doneCount":  0,
                         "pct":  0,
                         "milestones":  [
                                            {
                                                "name":  "Design and overview",
                                                "dateISO":  "2026-06-07"
                                            },
                                            {
                                                "name":  "How to actually Fab and implement design",
                                                "dateISO":  "2026-06-20"
                                            }
                                        ]
                     },
                     {
                         "name":  "SWC HI [CMI]",
                         "pm":  "Al Karloff",
                         "startISO":  "2024-12-01",
                         "finishISO":  "2026-05-09",
                         "taskCount":  5,
                         "doneCount":  5,
                         "pct":  100,
                         "milestones":  [

                                        ]
                     },
                     {
                         "name":  "SMC [Hamilton]",
                         "pm":  "Al Karloff",
                         "startISO":  "2025-10-05",
                         "finishISO":  "2026-06-27",
                         "taskCount":  33,
                         "doneCount":  24,
                         "pct":  73,
                         "milestones":  [
                                            {
                                                "name":  "Pre-Launch [April 27/26] [Indy]",
                                                "dateISO":  "2026-05-02"
                                            },
                                            {
                                                "name":  "Launch [TBD] [Michigan?]",
                                                "dateISO":  "2026-06-27"
                                            },
                                            {
                                                "name":  "Air Tank Delivery",
                                                "dateISO":  "2026-02-21"
                                            },
                                            {
                                                "name":  "Soft Launch",
                                                "dateISO":  "2026-04-25"
                                            },
                                            {
                                                "name":  "Compressor Delivery",
                                                "dateISO":  "2026-02-28"
                                            }
                                        ]
                     },
                     {
                         "name":  "Thunder Bay MRI Bus",
                         "pm":  "Al Karloff",
                         "startISO":  "2026-04-05",
                         "finishISO":  "2027-03-06",
                         "taskCount":  6,
                         "doneCount":  0,
                         "pct":  0,
                         "milestones":  [
                                            {
                                                "name":  "Launch?",
                                                "dateISO":  "2027-03-06"
                                            },
                                            {
                                                "name":  "Soft Launch / QS",
                                                "dateISO":  "2027-02-27"
                                            }
                                        ]
                     },
                     {
                         "name":  "Siemens 53ft Replacement #1",
                         "pm":  "TBD",
                         "startISO":  "2026-09-06",
                         "finishISO":  "2026-11-07",
                         "taskCount":  1,
                         "doneCount":  0,
                         "pct":  0,
                         "milestones":  [
                                            {
                                                "name":  "Q3 TARGET LAUNCH",
                                                "dateISO":  "2026-11-07"
                                            }
                                        ]
                     },
                     {
                         "name":  "Siemens 53ft Replacement #2",
                         "pm":  "TBD",
                         "startISO":  "2026-09-06",
                         "finishISO":  "2026-11-07",
                         "taskCount":  1,
                         "doneCount":  0,
                         "pct":  0,
                         "milestones":  [
                                            {
                                                "name":  "Q3 TARGET LAUNCH",
                                                "dateISO":  "2026-11-07"
                                            }
                                        ]
                     },
                     {
                         "name":  "Stryker",
                         "pm":  "Megan Fraser",
                         "startISO":  null,
                         "finishISO":  null,
                         "taskCount":  1,
                         "doneCount":  0,
                         "pct":  0,
                         "milestones":  [

                                        ]
                     }
                 ]
};
