// Auto-generated tour schedule data (imported from MyMobileTour calendars June-Oct 2026)
// Equipment/crew/hours are placeholders until the real lists are provided.
window.MMT_DATA = {
 "generatedText": "Tue Jun 16, 2026  10:30 PM",
 "todayISO": "2026-06-16",
 "tours": [
  {
   "name": "ABB",
   "color": "#5b8bd0"
  },
  {
   "name": "ABB - Grand Rapids, MI",
   "color": "#5fae7e"
  },
  {
   "name": "Aga Khan Foundation Canada",
   "color": "#cc9a52"
  },
  {
   "name": "BAC Roadshow",
   "color": "#9b86c9"
  },
  {
   "name": "Baxter CEC 2026",
   "color": "#5bb0a6"
  },
  {
   "name": "Boston Scientific - SX",
   "color": "#cf7f8c"
  },
  {
   "name": "Callaway Drop off",
   "color": "#6fa8c7"
  },
  {
   "name": "Callaway Pick up",
   "color": "#bba14e"
  },
  {
   "name": "Duracell Mobile Innovation Center",
   "color": "#6fa86f"
  },
  {
   "name": "Durastar Days (Ferguson)",
   "color": "#a98fc0"
  },
  {
   "name": "FM Risk Prevention Tour",
   "color": "#c98aa6"
  },
  {
   "name": "Hyperfine #2 (J1556)",
   "color": "#69a98f"
  },
  {
   "name": "Hyperfine - East (J1453)",
   "color": "#7a9bd0"
  },
  {
   "name": "JFSD - Jewish Open House",
   "color": "#bfa85e"
  },
  {
   "name": "JFSD - Mira Costa Community College",
   "color": "#cf9a6b"
  },
  {
   "name": "OS- Bloomfield Hills",
   "color": "#79b3aa"
  },
  {
   "name": "Omnicell (J1446)",
   "color": "#bf86c2"
  },
  {
   "name": "PSEG - Bayonne Hometown Fair",
   "color": "#8aa8cf"
  },
  {
   "name": "SWC FL 1 - Augustine Historical Society",
   "color": "#9ab36a"
  },
  {
   "name": "SWC FL 1 - Casa Ranch Montessori",
   "color": "#bf8585"
  },
  {
   "name": "SWC FL 1 - Historic Virginia Key Beach Park",
   "color": "#5b8bd0"
  },
  {
   "name": "SWC FL 1 - Mosaic Miami",
   "color": "#5fae7e"
  },
  {
   "name": "SWC FL 1 - PBC Lantana Library Branch",
   "color": "#cc9a52"
  },
  {
   "name": "SWC FL 1 - PBC Library Gardens Branch",
   "color": "#9b86c9"
  },
  {
   "name": "SWC FL 1 - PBC Library Main Branch",
   "color": "#5bb0a6"
  },
  {
   "name": "SWC FL 1 - PBC Library West Boynton Branch",
   "color": "#cf7f8c"
  },
  {
   "name": "SWC IL 1 - Park Forest Public Library",
   "color": "#6fa8c7"
  },
  {
   "name": "SWC IL1 - Evergreen Park Public Library",
   "color": "#bba14e"
  },
  {
   "name": "Saskatchewan Mammography Trailer One",
   "color": "#6fa86f"
  },
  {
   "name": "Saskatchewan Mammography Trailer Two",
   "color": "#a98fc0"
  },
  {
   "name": "Siemens DI eXplore tour 2026",
   "color": "#c98aa6"
  },
  {
   "name": "Sobeys 53\" MFX Summer Tour",
   "color": "#69a98f"
  },
  {
   "name": "Warhammer (J1434)",
   "color": "#7a9bd0"
  },
  {
   "name": "bioMerieux",
   "color": "#bfa85e"
  }
 ],
 "events": [
  {
   "id": "e86328987",
   "date": "2026-06-01",
   "tour": "Boston Scientific - SX",
   "city": "Glen Allen",
   "state": "VA",
   "venue": "Richmond Marriott Short Pump",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e80cf72b5",
   "date": "2026-06-01",
   "tour": "SWC FL 1 - Casa Ranch Montessori",
   "city": "Miramar",
   "state": "FL",
   "venue": "Casa Ranch Montessori",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e99c3a0ae",
   "date": "2026-06-01",
   "tour": "SWC IL 1 - Park Forest Public Library",
   "city": "Park Forest",
   "state": "IL",
   "venue": "Park Forest Public Library",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e75db41d0",
   "date": "2026-06-01",
   "tour": "Saskatchewan Mammography Trailer One",
   "city": "Fort Qu Appelle",
   "state": "SK",
   "venue": "All Nations Healing Hospital",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e49baf796",
   "date": "2026-06-01",
   "tour": "Saskatchewan Mammography Trailer Two",
   "city": "Outlook",
   "state": "SK",
   "venue": "Riverbend Co-op Food Store",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ed02f4842",
   "date": "2026-06-01",
   "tour": "Siemens DI eXplore tour 2026",
   "city": "Detroit",
   "state": "MI",
   "venue": "Huntington Place",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ee7d46989",
   "date": "2026-06-02",
   "tour": "ABB - Grand Rapids, MI",
   "city": "Grand Rapids",
   "state": "MI",
   "venue": "All Phase Electric",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e78ff9603",
   "date": "2026-06-02",
   "tour": "Hyperfine - East (J1453)",
   "city": "Pensacola",
   "state": "FL",
   "venue": "Sacred Heart Health System",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e3fccb707",
   "date": "2026-06-02",
   "tour": "OS- Bloomfield Hills",
   "city": "Bloomfield Hills",
   "state": "MI",
   "venue": "Bloomfield Hills High School",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ec8d2e9d8",
   "date": "2026-06-02",
   "tour": "SWC IL 1 - Park Forest Public Library",
   "city": "Park Forest",
   "state": "IL",
   "venue": "Park Forest Public Library",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e844d4716",
   "date": "2026-06-02",
   "tour": "Saskatchewan Mammography Trailer One",
   "city": "Fort Qu Appelle",
   "state": "SK",
   "venue": "All Nations Healing Hospital",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ec8ddcd78",
   "date": "2026-06-02",
   "tour": "Saskatchewan Mammography Trailer Two",
   "city": "Outlook",
   "state": "SK",
   "venue": "Riverbend Co-op Food Store",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e73da1755",
   "date": "2026-06-02",
   "tour": "Siemens DI eXplore tour 2026",
   "city": "Detroit",
   "state": "MI",
   "venue": "Huntington Place",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ed2999802",
   "date": "2026-06-03",
   "tour": "Callaway Pick up",
   "city": "Dublin",
   "state": "OH",
   "venue": "Muirfield Village",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e148cf83f",
   "date": "2026-06-03",
   "tour": "FM Risk Prevention Tour",
   "city": "North Chicago",
   "state": "IL",
   "venue": "Abbvie",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e7f43eb0d",
   "date": "2026-06-03",
   "tour": "Hyperfine #2 (J1556)",
   "city": "Minneapolis",
   "state": "MN",
   "venue": "Noran Neurology",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ebe2e77af",
   "date": "2026-06-03",
   "tour": "Hyperfine - East (J1453)",
   "city": "Pensacola",
   "state": "FL",
   "venue": "Sacred Heart Health System",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ea95767f0",
   "date": "2026-06-03",
   "tour": "JFSD - Jewish Open House",
   "city": "Encinitas",
   "state": "CA",
   "venue": "Coastal Roots Farms",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e447ad1ee",
   "date": "2026-06-03",
   "tour": "OS- Bloomfield Hills",
   "city": "Bloomfield Hills",
   "state": "MI",
   "venue": "Bloomfield Hills High School",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ee0aaa87f",
   "date": "2026-06-03",
   "tour": "SWC IL 1 - Park Forest Public Library",
   "city": "Park Forest",
   "state": "IL",
   "venue": "Park Forest Public Library",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e2ddc452a",
   "date": "2026-06-04",
   "tour": "Aga Khan Foundation Canada",
   "city": "Vancouver",
   "state": "BC",
   "venue": "The Station",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "edcaa54ff",
   "date": "2026-06-04",
   "tour": "Boston Scientific - SX",
   "city": "Charlotte",
   "state": "NC",
   "venue": "Trinity Presbyterian Church",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e2eb1acb5",
   "date": "2026-06-04",
   "tour": "JFSD - Jewish Open House",
   "city": "Encinitas",
   "state": "CA",
   "venue": "Coastal Roots Farms",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e1aed779d",
   "date": "2026-06-04",
   "tour": "OS- Bloomfield Hills",
   "city": "Bloomfield Hills",
   "state": "MI",
   "venue": "Bloomfield Hills High School",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e06abcebe",
   "date": "2026-06-04",
   "tour": "Omnicell (J1446)",
   "city": "Pensacola",
   "state": "FL",
   "venue": "Sacred Heart Health System",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ef6363b15",
   "date": "2026-06-04",
   "tour": "SWC IL 1 - Park Forest Public Library",
   "city": "Park Forest",
   "state": "IL",
   "venue": "Park Forest Public Library",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e83161fca",
   "date": "2026-06-04",
   "tour": "Saskatchewan Mammography Trailer Two",
   "city": "Outlook",
   "state": "SK",
   "venue": "",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e3a308dc7",
   "date": "2026-06-05",
   "tour": "Aga Khan Foundation Canada",
   "city": "Vancouver",
   "state": "BC",
   "venue": "The Station",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ea5b86847",
   "date": "2026-06-05",
   "tour": "Boston Scientific - SX",
   "city": "Greenville",
   "state": "SC",
   "venue": "Prisma Health Greenville Memorial Hospital",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e0893c6bd",
   "date": "2026-06-05",
   "tour": "JFSD - Mira Costa Community College",
   "city": "Cardiff",
   "state": "CA",
   "venue": "MiraCosta College, San Elijo Campus",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e3d931c12",
   "date": "2026-06-05",
   "tour": "OS- Bloomfield Hills",
   "city": "Bloomfield Hills",
   "state": "MI",
   "venue": "Bloomfield Hills High School",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e68844e7d",
   "date": "2026-06-05",
   "tour": "SWC IL 1 - Park Forest Public Library",
   "city": "Park Forest",
   "state": "IL",
   "venue": "Park Forest Public Library",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e2fe79167",
   "date": "2026-06-05",
   "tour": "bioMerieux",
   "city": "Washington",
   "state": "DC",
   "venue": "Walter E Washington Convention Center",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e29fe3da2",
   "date": "2026-06-06",
   "tour": "Aga Khan Foundation Canada",
   "city": "Vancouver",
   "state": "BC",
   "venue": "The Station",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e2f29bf36",
   "date": "2026-06-06",
   "tour": "Callaway Pick up",
   "city": "Carlsbad",
   "state": "CA",
   "venue": "Callaway HQ",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ec52db6c2",
   "date": "2026-06-06",
   "tour": "PSEG - Bayonne Hometown Fair",
   "city": "Bayonne",
   "state": "NJ",
   "venue": "Bayonne Hometown Fair",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ec4a8e626",
   "date": "2026-06-06",
   "tour": "Saskatchewan Mammography Trailer One",
   "city": "Fort Qu Appelle",
   "state": "SK",
   "venue": "All Nations Healing Hospital",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e3c5ff1f9",
   "date": "2026-06-06",
   "tour": "bioMerieux",
   "city": "Washington",
   "state": "DC",
   "venue": "Walter E Washington Convention Center",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e33188e29",
   "date": "2026-06-07",
   "tour": "Aga Khan Foundation Canada",
   "city": "Vancouver",
   "state": "BC",
   "venue": "The Station",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e93028e7a",
   "date": "2026-06-07",
   "tour": "Callaway Drop off",
   "city": "Greensboro",
   "state": "NC",
   "venue": "Sedgefield Country Club",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "efd92504b",
   "date": "2026-06-07",
   "tour": "Saskatchewan Mammography Trailer One",
   "city": "Fort Qu Appelle",
   "state": "SK",
   "venue": "All Nations Healing Hospital",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ed2602d8a",
   "date": "2026-06-07",
   "tour": "bioMerieux",
   "city": "Washington",
   "state": "DC",
   "venue": "Walter E Washington Convention Center",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e2ddc1342",
   "date": "2026-06-08",
   "tour": "Aga Khan Foundation Canada",
   "city": "Vancouver",
   "state": "BC",
   "venue": "The Station",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ec7ddcbd9",
   "date": "2026-06-08",
   "tour": "Boston Scientific - SX",
   "city": "Cherry Hill",
   "state": "NJ",
   "venue": "DoubleTree by Hilton Cherrywood Philadelphia",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e188b9157",
   "date": "2026-06-08",
   "tour": "Hyperfine #2 (J1556)",
   "city": "Minneapolis",
   "state": "MN",
   "venue": "University Minnesota Fairview",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e1022e6dc",
   "date": "2026-06-08",
   "tour": "Saskatchewan Mammography Trailer One",
   "city": "Fort Qu Appelle",
   "state": "SK",
   "venue": "All Nations Healing Hospital",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ec6e04ea7",
   "date": "2026-06-09",
   "tour": "Aga Khan Foundation Canada",
   "city": "Vancouver",
   "state": "BC",
   "venue": "The Station",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e74438314",
   "date": "2026-06-09",
   "tour": "BAC Roadshow",
   "city": "Madison",
   "state": "WI",
   "venue": "Masters Building Solutions",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e1002aadb",
   "date": "2026-06-09",
   "tour": "Boston Scientific - SX",
   "city": "Cherry Hill",
   "state": "NJ",
   "venue": "DoubleTree by Hilton Cherrywood Philadelphia",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e27dca511",
   "date": "2026-06-09",
   "tour": "Callaway Pick up",
   "city": "Greensboro",
   "state": "NC",
   "venue": "Sedgefield Country Club",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e9662d7ca",
   "date": "2026-06-09",
   "tour": "Hyperfine #2 (J1556)",
   "city": "Elk Grove Village",
   "state": "IL",
   "venue": "Alexian Brothers Medical Center",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "eb5164fb9",
   "date": "2026-06-09",
   "tour": "Saskatchewan Mammography Trailer One",
   "city": "Fort Qu Appelle",
   "state": "SK",
   "venue": "All Nations Healing Hospital",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ef7c92c9d",
   "date": "2026-06-10",
   "tour": "Aga Khan Foundation Canada",
   "city": "Vancouver",
   "state": "BC",
   "venue": "The Station",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e5b5239ce",
   "date": "2026-06-10",
   "tour": "Boston Scientific - SX",
   "city": "Cherry Hill",
   "state": "NJ",
   "venue": "DoubleTree by Hilton Cherrywood Philadelphia",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e361c53c2",
   "date": "2026-06-10",
   "tour": "Callaway Drop off",
   "city": "Madison Heights",
   "state": "MI",
   "venue": "MRA Facility",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e640259da",
   "date": "2026-06-10",
   "tour": "Saskatchewan Mammography Trailer One",
   "city": "Fort Qu Appelle",
   "state": "SK",
   "venue": "All Nations Healing Hospital",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e6f40d81e",
   "date": "2026-06-10",
   "tour": "Siemens DI eXplore tour 2026",
   "city": "Bradley",
   "state": "IL",
   "venue": "CSL Behring",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e0e97bc86",
   "date": "2026-06-11",
   "tour": "Aga Khan Foundation Canada",
   "city": "Vancouver",
   "state": "BC",
   "venue": "The Station",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ee7632485",
   "date": "2026-06-11",
   "tour": "Boston Scientific - SX",
   "city": "Iselin",
   "state": "NJ",
   "venue": "Marriott Delta Hotel Woodbridge",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "eb83fe7fd",
   "date": "2026-06-11",
   "tour": "Hyperfine #2 (J1556)",
   "city": "Franklin",
   "state": "WI",
   "venue": "Ascension Milwaukee",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ebf4727f2",
   "date": "2026-06-11",
   "tour": "Saskatchewan Mammography Trailer One",
   "city": "Fort Qu Appelle",
   "state": "SK",
   "venue": "All Nations Healing Hospital",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e88d0252f",
   "date": "2026-06-12",
   "tour": "BAC Roadshow",
   "city": "Akron",
   "state": "OH",
   "venue": "Mark Elliot Company",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e1db8bd93",
   "date": "2026-06-12",
   "tour": "SWC IL1 - Evergreen Park Public Library",
   "city": "Evergreen Park",
   "state": "IL",
   "venue": "Evergreen Park Public Library",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e5c5614ba",
   "date": "2026-06-12",
   "tour": "Saskatchewan Mammography Trailer One",
   "city": "Fort Qu Appelle",
   "state": "SK",
   "venue": "All Nations Healing Hospital",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e1a47ff8f",
   "date": "2026-06-13",
   "tour": "Callaway Drop off",
   "city": "Southampton",
   "state": "NY",
   "venue": "Shinnecock Hills",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e429de0df",
   "date": "2026-06-13",
   "tour": "SWC FL 1 - Historic Virginia Key Beach Park",
   "city": "Miami",
   "state": "FL",
   "venue": "Historic Virginia Keys Park",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e22090f7d",
   "date": "2026-06-15",
   "tour": "Baxter CEC 2026",
   "city": "Deerfield",
   "state": "IL",
   "venue": "Baxter HQ",
   "status": "Complete",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e932c6f32",
   "date": "2026-06-16",
   "tour": "BAC Roadshow",
   "city": "Pontiac",
   "state": "MI",
   "venue": "M1",
   "status": "Active",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e4d9f729d",
   "date": "2026-06-16",
   "tour": "SWC FL 1 - Mosaic Miami",
   "city": "Miami Shores",
   "state": "FL",
   "venue": "Mosaic Miami",
   "status": "Active",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ee11ffa25",
   "date": "2026-06-16",
   "tour": "Warhammer (J1434)",
   "city": "Edmonton",
   "state": "AB",
   "venue": "Edmonton EXPO Centre",
   "status": "Active",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e52cb0ea3",
   "date": "2026-06-17",
   "tour": "Warhammer (J1434)",
   "city": "Edmonton",
   "state": "AB",
   "venue": "Edmonton EXPO Centre",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ec42f448f",
   "date": "2026-06-18",
   "tour": "Aga Khan Foundation Canada",
   "city": "Beaumont",
   "state": "AB",
   "venue": "Bibliotheque de Beaumont Library",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e0cc0d443",
   "date": "2026-06-18",
   "tour": "BAC Roadshow",
   "city": "Hudson",
   "state": "ON",
   "venue": "Dave & Buster's Vaughan",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ecb2c2bab",
   "date": "2026-06-18",
   "tour": "Duracell Mobile Innovation Center",
   "city": "Minneapolis",
   "state": "MN",
   "venue": "Music Wall Parking Lot",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ec222ed8d",
   "date": "2026-06-18",
   "tour": "SWC FL 1 - Augustine Historical Society",
   "city": "",
   "state": "",
   "venue": "",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e06b345c0",
   "date": "2026-06-18",
   "tour": "Warhammer (J1434)",
   "city": "Edmonton",
   "state": "AB",
   "venue": "Edmonton EXPO Centre",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "eb886f61d",
   "date": "2026-06-19",
   "tour": "ABB",
   "city": "Coronado",
   "state": "CA",
   "venue": "Naval Base",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e2a4db72f",
   "date": "2026-06-19",
   "tour": "Aga Khan Foundation Canada",
   "city": "Beaumont",
   "state": "AB",
   "venue": "Bibliotheque de Beaumont Library",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e79008b57",
   "date": "2026-06-19",
   "tour": "Callaway Pick up",
   "city": "Madison Heights",
   "state": "MI",
   "venue": "MRA Facility",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ecbe67a19",
   "date": "2026-06-20",
   "tour": "ABB",
   "city": "Coronado",
   "state": "CA",
   "venue": "Naval Base",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e93906316",
   "date": "2026-06-20",
   "tour": "Aga Khan Foundation Canada",
   "city": "Beaumont",
   "state": "AB",
   "venue": "Bibliotheque de Beaumont Library",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e61c40dbd",
   "date": "2026-06-20",
   "tour": "SWC FL 1 - PBC Lantana Library Branch",
   "city": "Lake Worth",
   "state": "FL",
   "venue": "PBC Lantana Library Branch",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e70dbe2d4",
   "date": "2026-06-21",
   "tour": "ABB",
   "city": "Coronado",
   "state": "CA",
   "venue": "Naval Base",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "eaafaa3b3",
   "date": "2026-06-21",
   "tour": "Aga Khan Foundation Canada",
   "city": "Beaumont",
   "state": "AB",
   "venue": "Bibliotheque de Beaumont Library",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e38b2d1c3",
   "date": "2026-06-21",
   "tour": "Callaway Drop off",
   "city": "Chaska",
   "state": "MN",
   "venue": "Hazeltine National Golf Club",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ec15983d4",
   "date": "2026-06-21",
   "tour": "Warhammer (J1434)",
   "city": "Edmonton",
   "state": "AB",
   "venue": "Edmonton EXPO Centre",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "eadbfd8e6",
   "date": "2026-06-22",
   "tour": "Aga Khan Foundation Canada",
   "city": "Beaumont",
   "state": "AB",
   "venue": "Bibliotheque de Beaumont Library",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e9ccb3a7a",
   "date": "2026-06-22",
   "tour": "BAC Roadshow",
   "city": "Canton",
   "state": "MA",
   "venue": "Topgolf",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e4608487b",
   "date": "2026-06-22",
   "tour": "Baxter CEC 2026",
   "city": "Charlottesville",
   "state": "VA",
   "venue": "Sentara Martha Jefferson Hospital",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e916079c6",
   "date": "2026-06-22",
   "tour": "Omnicell (J1446)",
   "city": "Austin",
   "state": "TX",
   "venue": "Ascension Seton Medical Center Austin",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ee534faa7",
   "date": "2026-06-22",
   "tour": "Siemens DI eXplore tour 2026",
   "city": "Chicago",
   "state": "IL",
   "venue": "McCormick Place Marshalling Yard",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "edc5c8e07",
   "date": "2026-06-23",
   "tour": "Aga Khan Foundation Canada",
   "city": "Beaumont",
   "state": "AB",
   "venue": "Bibliotheque de Beaumont Library",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ec148d8b6",
   "date": "2026-06-23",
   "tour": "Baxter CEC 2026",
   "city": "Charlottesville",
   "state": "VA",
   "venue": "Sentara Martha Jefferson Hospital",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ee0b9d241",
   "date": "2026-06-23",
   "tour": "Omnicell (J1446)",
   "city": "Austin",
   "state": "TX",
   "venue": "Ascension Seton Medical Center Austin",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "efeeca7db",
   "date": "2026-06-23",
   "tour": "SWC FL 1 - PBC Library West Boynton Branch",
   "city": "Boynton Beach",
   "state": "FL",
   "venue": "PBS Library West Boynton Beach",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ebd8dbfd3",
   "date": "2026-06-23",
   "tour": "Siemens DI eXplore tour 2026",
   "city": "Chicago",
   "state": "IL",
   "venue": "McCormick Place Marshalling Yard",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ef19686e9",
   "date": "2026-06-23",
   "tour": "bioMerieux",
   "city": "Bethlehem",
   "state": "PA",
   "venue": "St. Luke's Fitness & Sports Performance Center - Bethlehem",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "efe46d463",
   "date": "2026-06-24",
   "tour": "Aga Khan Foundation Canada",
   "city": "Beaumont",
   "state": "AB",
   "venue": "Bibliotheque de Beaumont Library",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e9cf75adb",
   "date": "2026-06-24",
   "tour": "Callaway Pick up",
   "city": "Chaska",
   "state": "MN",
   "venue": "Hazeltine National Golf Club",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e2b14ca65",
   "date": "2026-06-24",
   "tour": "Siemens DI eXplore tour 2026",
   "city": "Chicago",
   "state": "IL",
   "venue": "McCormick Place Marshalling Yard",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e65cb7c5a",
   "date": "2026-06-24",
   "tour": "bioMerieux",
   "city": "Bethlehem",
   "state": "PA",
   "venue": "St. Luke's Fitness & Sports Performance Center - Bethlehem",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ec19b2940",
   "date": "2026-06-25",
   "tour": "Aga Khan Foundation Canada",
   "city": "Beaumont",
   "state": "AB",
   "venue": "Bibliotheque de Beaumont Library",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e13e63c73",
   "date": "2026-06-25",
   "tour": "Callaway Drop off",
   "city": "St. Charles",
   "state": "MO",
   "venue": "Craftsman Industries",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e64c991e2",
   "date": "2026-06-25",
   "tour": "SWC FL 1 - PBC Library Gardens Branch",
   "city": "Palm Beach",
   "state": "FL",
   "venue": "PBC Gardens Library",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e46463c1b",
   "date": "2026-06-25",
   "tour": "Siemens DI eXplore tour 2026",
   "city": "Chicago",
   "state": "IL",
   "venue": "McCormick Place Marshalling Yard",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "edcaa9f52",
   "date": "2026-06-26",
   "tour": "Aga Khan Foundation Canada",
   "city": "Beaumont",
   "state": "AB",
   "venue": "Bibliotheque de Beaumont Library",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ee92975ed",
   "date": "2026-06-26",
   "tour": "BAC Roadshow",
   "city": "Lenhartsville",
   "state": "PA",
   "venue": "The Barn at Walnut Grove",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e6be96ca3",
   "date": "2026-06-27",
   "tour": "Aga Khan Foundation Canada",
   "city": "Beaumont",
   "state": "AB",
   "venue": "Bibliotheque de Beaumont Library",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "edfa9b6ea",
   "date": "2026-06-27",
   "tour": "SWC FL 1 - PBC Library Main Branch",
   "city": "West Palm Beach",
   "state": "FL",
   "venue": "PBC Library Main Branch",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ed0e5202f",
   "date": "2026-06-30",
   "tour": "BAC Roadshow",
   "city": "Jessup",
   "state": "MD",
   "venue": "Baltimore Aircoil Company",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e56ae1042",
   "date": "2026-06-30",
   "tour": "Siemens DI eXplore tour 2026",
   "city": "West Chester",
   "state": "OH",
   "venue": "E-Tech Group",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e3680584a",
   "date": "2026-07-02",
   "tour": "BAC Roadshow",
   "city": "Cranberry",
   "state": "PA",
   "venue": "Havtech",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e95212754",
   "date": "2026-07-02",
   "tour": "Sobeys 53\" MFX Summer Tour",
   "city": "Calgary",
   "state": "AB",
   "venue": "Calgary Stampede",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ed1cdd315",
   "date": "2026-07-03",
   "tour": "Sobeys 53\" MFX Summer Tour",
   "city": "Calgary",
   "state": "AB",
   "venue": "Calgary Stampede",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "efe54c13e",
   "date": "2026-07-04",
   "tour": "Sobeys 53\" MFX Summer Tour",
   "city": "Calgary",
   "state": "AB",
   "venue": "Calgary Stampede",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ed4f6b056",
   "date": "2026-07-05",
   "tour": "Sobeys 53\" MFX Summer Tour",
   "city": "Calgary",
   "state": "AB",
   "venue": "Calgary Stampede",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ed3100b54",
   "date": "2026-07-06",
   "tour": "Sobeys 53\" MFX Summer Tour",
   "city": "Calgary",
   "state": "AB",
   "venue": "Calgary Stampede",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e05c9c5b2",
   "date": "2026-07-07",
   "tour": "BAC Roadshow",
   "city": "Coralville",
   "state": "IA",
   "venue": "Mechanical Sales",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "eca743e5a",
   "date": "2026-07-07",
   "tour": "Sobeys 53\" MFX Summer Tour",
   "city": "Calgary",
   "state": "AB",
   "venue": "Calgary Stampede",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e71dc0cf4",
   "date": "2026-07-08",
   "tour": "Boston Scientific - SX",
   "city": "Ann Arbor",
   "state": "MI",
   "venue": "University of Michigan Medical Center",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e07cb46b4",
   "date": "2026-07-08",
   "tour": "Sobeys 53\" MFX Summer Tour",
   "city": "Calgary",
   "state": "AB",
   "venue": "Calgary Stampede",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e9a0b2129",
   "date": "2026-07-09",
   "tour": "BAC Roadshow",
   "city": "Lincoln",
   "state": "NE",
   "venue": "TBD Lincoln",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ecc8f4712",
   "date": "2026-07-09",
   "tour": "Sobeys 53\" MFX Summer Tour",
   "city": "Calgary",
   "state": "AB",
   "venue": "Calgary Stampede",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ebe38d223",
   "date": "2026-07-10",
   "tour": "Sobeys 53\" MFX Summer Tour",
   "city": "Calgary",
   "state": "AB",
   "venue": "Calgary Stampede",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ea5eb050f",
   "date": "2026-07-11",
   "tour": "Boston Scientific - SX",
   "city": "Louisville",
   "state": "KY",
   "venue": "Hilton Garden Inn Louisville Mall of St. Matthews",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "eb27e697a",
   "date": "2026-07-11",
   "tour": "Sobeys 53\" MFX Summer Tour",
   "city": "Calgary",
   "state": "AB",
   "venue": "Calgary Stampede",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e874ee3b4",
   "date": "2026-07-12",
   "tour": "Sobeys 53\" MFX Summer Tour",
   "city": "Calgary",
   "state": "AB",
   "venue": "Calgary Stampede",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e9970cfe1",
   "date": "2026-07-14",
   "tour": "Durastar Days (Ferguson)",
   "city": "Sugar Land",
   "state": "TX",
   "venue": "Ferguson",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e9b3b08a3",
   "date": "2026-07-15",
   "tour": "Durastar Days (Ferguson)",
   "city": "Houston",
   "state": "TX",
   "venue": "Farrago",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e8a1b8551",
   "date": "2026-07-16",
   "tour": "BAC Roadshow",
   "city": "Calgary",
   "state": "AB",
   "venue": "TBD",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e7805337b",
   "date": "2026-07-16",
   "tour": "Durastar Days (Ferguson)",
   "city": "Spring",
   "state": "TX",
   "venue": "",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e1a6dcd3f",
   "date": "2026-07-17",
   "tour": "Boston Scientific - SX",
   "city": "Milwaukee",
   "state": "WI",
   "venue": "Medical College of Wisconsin",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ed2189feb",
   "date": "2026-07-20",
   "tour": "BAC Roadshow",
   "city": "Edmonton",
   "state": "AB",
   "venue": "TBD Edmonton",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ea6c15f0c",
   "date": "2026-07-21",
   "tour": "Durastar Days (Ferguson)",
   "city": "San Antonio",
   "state": "TX",
   "venue": "Ferguson",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "efb9155b5",
   "date": "2026-07-22",
   "tour": "Durastar Days (Ferguson)",
   "city": "Del Valle",
   "state": "TX",
   "venue": "Ferguson",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ee99e7f3f",
   "date": "2026-07-23",
   "tour": "Durastar Days (Ferguson)",
   "city": "Round Rock",
   "state": "TX",
   "venue": "Ferguson",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ebecf1da1",
   "date": "2026-07-24",
   "tour": "FM Risk Prevention Tour",
   "city": "Germantown",
   "state": "WI",
   "venue": "Gehl Foods",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e2d3b9ae7",
   "date": "2026-07-28",
   "tour": "FM Risk Prevention Tour",
   "city": "Saukville",
   "state": "WI",
   "venue": "Charter Steel Saukville",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e0b91abc4",
   "date": "2026-08-07",
   "tour": "FM Risk Prevention Tour",
   "city": "Chicago",
   "state": "IL",
   "venue": "Franciscan Health",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ef164755a",
   "date": "2026-08-11",
   "tour": "FM Risk Prevention Tour",
   "city": "Newburgh",
   "state": "IN",
   "venue": "Deaconess",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e288b6728",
   "date": "2026-09-01",
   "tour": "Baxter CEC 2026",
   "city": "Portland",
   "state": "OR",
   "venue": "Providence Portland Medical Center",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e0f0c2b50",
   "date": "2026-09-02",
   "tour": "Baxter CEC 2026",
   "city": "Portland",
   "state": "OR",
   "venue": "Providence Portland Medical Center",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e1bf7ab42",
   "date": "2026-09-06",
   "tour": "Baxter CEC 2026",
   "city": "Sacramento",
   "state": "CA",
   "venue": "Sutter Health Corporate Office",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e89ce38fe",
   "date": "2026-09-07",
   "tour": "Baxter CEC 2026",
   "city": "Sacramento",
   "state": "CA",
   "venue": "Sutter Health Corporate Office",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e82283c80",
   "date": "2026-09-15",
   "tour": "Baxter CEC 2026",
   "city": "Spokane",
   "state": "WA",
   "venue": "Providence Sacred Heart Med Ctr/Children's Hospital",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "eddf51938",
   "date": "2026-09-16",
   "tour": "Baxter CEC 2026",
   "city": "Spokane",
   "state": "WA",
   "venue": "Providence Sacred Heart Med Ctr/Children's Hospital",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e04ba4958",
   "date": "2026-09-22",
   "tour": "Baxter CEC 2026",
   "city": "Renton",
   "state": "WA",
   "venue": "Providence Health & Services",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e4ebdbc3e",
   "date": "2026-09-23",
   "tour": "Baxter CEC 2026",
   "city": "Renton",
   "state": "WA",
   "venue": "Providence Health & Services",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e8ce9d552",
   "date": "2026-10-06",
   "tour": "Baxter CEC 2026",
   "city": "Sacramento",
   "state": "CA",
   "venue": "Sutter Health Corporate Office",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e261d46e2",
   "date": "2026-10-07",
   "tour": "Baxter CEC 2026",
   "city": "Sacramento",
   "state": "CA",
   "venue": "Sutter Health Corporate Office",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e4df8afef",
   "date": "2026-10-13",
   "tour": "Baxter CEC 2026",
   "city": "Oakland",
   "state": "CA",
   "venue": "Sutter Alta Bates Summit Medical Center",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e6ea2459c",
   "date": "2026-10-14",
   "tour": "Baxter CEC 2026",
   "city": "Oakland",
   "state": "CA",
   "venue": "Sutter Alta Bates Summit Medical Center",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e5ff6b724",
   "date": "2026-10-20",
   "tour": "Baxter CEC 2026",
   "city": "Boise",
   "state": "ID",
   "venue": "St. Luke's Boise Medical Center",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e68a25564",
   "date": "2026-10-21",
   "tour": "Baxter CEC 2026",
   "city": "Boise",
   "state": "ID",
   "venue": "St. Luke's Boise Medical Center",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "e3af22508",
   "date": "2026-10-27",
   "tour": "Baxter CEC 2026",
   "city": "Salt Lake City",
   "state": "UT",
   "venue": "Intermountain Health Hospital",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  },
  {
   "id": "ed8b9bdce",
   "date": "2026-10-28",
   "tour": "Baxter CEC 2026",
   "city": "Salt Lake City",
   "state": "UT",
   "venue": "Intermountain Health Hospital",
   "status": "Scheduled",
   "crew": [],
   "equipment": [],
   "notes": ""
  }
 ],
 "equipment": [
  {
   "id": "eq1",
   "type": "Truck",
   "name": "Tractor 1 (T-101)",
   "active": true
  },
  {
   "id": "eq2",
   "type": "Truck",
   "name": "Tractor 2 (T-102)",
   "active": true
  },
  {
   "id": "eq3",
   "type": "Vehicle",
   "name": "Sprinter Van (V-201)",
   "active": true
  },
  {
   "id": "eq4",
   "type": "Generator",
   "name": "Generator 50kW (G-11)",
   "active": true
  }
 ],
 "people": [],
 "logs": [],
 "sample": true
};
